---
title: "Resume"
author: "Zihan Lin"
output: html_document
---

# My Resume

## Professional Experience
  
**Data Analyst Intern**
**EasyTransfer, Beijing**
**Jan 2024 - Feb 2024**
- Analyzed datasets to identify trends, improving decision-making processes.
- Worked closely with teams from other countries to streamline data collection methods, enhancing efficiency and ensuring data accuracy for better project outcomes.
- Quickly adapted to new tools and methodologies, demonstrating a strong work ethic and commitment to punctuality and continuous learning.
- Assisted in developing data-driven solutions, fostering a supportive environment that encouraged knowledge sharing and skill development.
- Optimized data visualization techniques, enabling stakeholders to grasp complex insights swiftly, thus enhancing decision-making clarity.
- Conducted thorough data validation checks, ensuring high accuracy levels in reporting, which led to more confident strategic decisions.

**Software Engineer Intern**
**AiME**
**Jul 2023 - Aug 2023**
- Led the development of a comprehensive automatic translator app, supporting over 50 languages, on the iOS simulator.
- Facilitated team communication to streamline project timelines, ensuring successful deployment within set deadlines.
- Introduced novel algorithms to improve translation accuracy, enhancing the app's competitive edge in the market.
- Implemented features that boosted user engagement, contributing to app's positive feedback and increased downloads.
- Conducted thorough code reviews to maintain high quality standards, minimizing bugs and enhancing overall app reliability.

**Production Assistant**
**Centerstage, Chicago**
**May 2023 - Jul 2023**
- Supported audio operations for live shows, enhancing sound quality and audience satisfaction.
- Provided backstage technical support, ensuring high-quality live performance production.
- Collaborated with production team to achieve technical excellence and successful show outcomes.
- Diagnosed and resolved complex audio issues promptly, ensuring uninterrupted show flow and maintaining high production standards.
- Facilitated seamless communication between technical and creative teams, fostering a cohesive environment for successful show execution.
- Streamlined backstage operations, reducing setup time and increasing efficiency, contributing to the smooth operation of live events.

**Data Analyst Intern**
**EasyTransfer, Beijing**
**Jan 2024 - Feb 2024**
- Collected and organized key data sets, boosting database efficiency and team data access.
- Enhanced data categorization using advanced SQL and Excel, improving usability for team members.
- Streamlined data visualization techniques, enhancing decision-making speed and accuracy within the team.
- Developed predictive models to forecast trends, providing actionable insights for strategic planning.
- Identified key data patterns, driving operational adjustments that led to measurable improvements in productivity.
- Conducted thorough data audits, ensuring accuracy and compliance with industry standards, bolstering trust in data outputs.
- Led cross-departmental workshops to foster data-driven decision-making culture, significantly enhancing inter-team collaboration.


## Education

**Master of Science**
**Biostatistics**
- Columbia University, Aug 2024 - Present

**Bachelor of Science**
**Computer Information Technology & Statistics**
- Purdue University, Aug 2020 - Dec 2023

## Skills

- Data analysis (R, Python)
- Coding (Java, C)
- Data visualization (Tableau, PowerBI)
- Statistics
- Micro PC (Raspberry Pi, Arduino)
- Sound mixing
- Git, GitHub, version control